    thread: <source loc="                                   vk_test_err.c:  11"> <proc_local id="   1" active="f" blocked="f"> <thread stage="                          erring()[                                   vk_test_err.c:  47@  -1]">: ERR Before error is raised.
    thread: <source loc="                                   vk_test_err.c:  13"> <proc_local id="   1" active="f" blocked="f"> <thread stage="                          erring()[                                   vk_test_err.c:  47@  -1]">: ERR somefunction: No such file or directory
    thread: <source loc="                                   vk_test_err.c:  20"> <proc_local id="   1" active="t" blocked="f"> <thread stage="                          erring()[                                   vk_test_err.c:  14@  -2]">: ERR Caught error: No such file or directory
    thread: <source loc="                                   vk_test_err.c:  16"> <proc_local id="   1" active="t" blocked="f"> <thread stage="                          erring()[                                   vk_test_err.c:  14@   4]">: ERR After error is raised.
    thread: <source loc="                                   vk_test_err.c:  23"> <proc_local id="   1" active="t" blocked="f"> <thread stage="                          erring()[                                   vk_test_err.c:  14@   4]">: ERR Error is cleaned up.
